CREATE TABLE Posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  excerpt VARCHAR(255)
);

CREATE TABLE Comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  postId INT NOT NULL,
  text VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  FOREIGN KEY (postId) REFERENCES Posts(id)
);
